export const AssetKeys = {
  TILES: {
    FLOOR: 'tile_floor',
    WALL: 'tile_wall',
    SHELF_BASE: 'tile_shelf_base',
    FLOOR_P0: 'tile_floor_p0',
    FLOOR_P1: 'tile_floor_p1',
    FLOOR_P2: 'tile_floor_p2',
    FLOOR_P3: 'tile_floor_p3',
    FLOOR_P4: 'tile_floor_p4',
    CONVEYOR_H: 'tile_conveyor_h',
    CONVEYOR_V: 'tile_conveyor_v',
    SLIPPERY: 'tile_slippery',
  },
  PLAYER: {
    SHEET: 'player_sheet',
    WALK_N: 'player_walk_n',
    WALK_NE: 'player_walk_ne',
    WALK_E: 'player_walk_e',
    WALK_SE: 'player_walk_se',
    WALK_S: 'player_walk_s',
    WALK_SW: 'player_walk_sw',
    WALK_W: 'player_walk_w',
    WALK_NW: 'player_walk_nw',
    IDLE: 'player_idle',
    CARRY: 'player_carry',
    // Aseprite PNG asset keys (per-direction)
    IDLE_PNG: 'player_idle_png',
    WALK_SE_PNG: 'player_walk_se_png',
    WALK_NE_PNG: 'player_walk_ne_png',
    CARRY_SE_PNG: 'player_carry_se_png',
    CARRY_NE_PNG: 'player_carry_ne_png',
  },
  FORKLIFT: {
    SHEET: 'forklift_sheet',
    IDLE: 'forklift_idle',
    MOVE: 'forklift_move',
    NE_PNG: 'forklift_ne_png',
    SE_PNG: 'forklift_se_png',
    SW_PNG: 'forklift_sw_png',
    NW_PNG: 'forklift_nw_png',
  },
  BOXES: {
    LAGER: 'box_lager',
    ALE: 'box_ale',
    STOUT: 'box_stout',
    PILSNER: 'box_pilsner',
  },
  UI: {
    PANEL: 'ui_panel',
    TIMER_BG: 'ui_timer_bg',
  },
} as const;
